#include "Player.h"
#include <iostream>

// here, copy construction is called, its always generated by compiler if doesnt created
// Player p is the copied from empty in this example
// When function ended, Player p will destructed
void display_player(Player p) {
    std::cout << "Name: " << p.get_name() << std::endl;
    std::cout << "Health: " << p.get_health() << std::endl;
    std::cout << "XP: " << p.get_xp() << std::endl;
}

int main() {
    Player empty;

    display_player(empty);

    Player hero("Hero");
    Player villain("Villain", 100, 12);

    return 0;
}

